---
title: 故事？往事？（二）
author: LEE
date: '2022-03-02'
slug: story1
categories:
  - story
tags:
  - Caprice
---

-1-

在我上小学三年级的时候，一天晚上，我做了一个奇怪的梦。梦中的幕天席地，望着漆黑一片的天空。

突然，天上坠落一块巨石压在我的胸口上。我被惊醒了，醒来的时候，窗外的夜空繁星点点。

第二天我把梦里的事情告诉了奶奶。奶奶找了一个解梦的先生来替我解梦。先生说，“石乃孤星，小子既梦此梦，谓之命犯孤星”云云。说我注定一世孤单。我当时并不懂什么叫孤单，但是却被眼前手舞足蹈的先生吓到了，不由自主的躲在奶奶的背后。奶奶没有听先生把话说完就把他轰走了。

许多年后，当我明白什么叫“一世孤单”的时候，才知道那解梦先生的话竟是如此严重。

每次我想起那个梦的时候，心里就会有点不舒服。母亲知道了我的想法后，笑骂，“不就是个梦嘛，你个傻小子还当真了。”听到母亲的话，我自己也笑了。

那时，奶奶已经去世几年了。

-2-

每当想念奶奶的时候，我都忍不住想哭。

奶奶一生生下了7个孩子，我父亲排行老3。在我父亲8岁那年，我爷爷撒手西去，留下了我奶奶和7个嗷嗷待哺的孩子。可以想象当时的社会，家庭中没有一个男人的生活会有多困难。但是奶奶是个坚强的女人，她独立支撑着整个家。这负担并没有压弯她的腰，反而让她的腰板更加的硬朗，更加坚挺。

用含辛茹苦来形容奶奶绝不夸张。

很多年后，当我刚出生的时候，我在奶奶的怀抱里睡得那么安静。

在我刚懂事的时候，我在奶奶怀里翻开往昔的黑白相册。我的小手在照片上指来指去问这问那，而奶奶则耐心的慈祥的告诉我这是谁，那又是谁。很快，翻到了相册的最后一页。我指着照片上的人等着奶奶的回答，奶奶却一直沉默不语。母亲看到了，将我从奶奶的怀抱中拉走。当我回头看时，奶奶双手捧着相册仔细的端详，微笑的脸上挂着晶莹的泪珠。

我问，“妈妈，妈妈，奶奶为什么哭了？”

“嘘，“妈妈说，”别去打扰奶奶啊，乖。”

“哦”。我又一次转过不解的脸看着奶奶脸上的泪珠悄然落地。

许多年后，当我最后一次翻开相册的最后一页时，看到了上面唯一的一幅照片。泛黄的照片上，年轻的奶奶和年轻的爷爷坐在椅子上，正在向我微笑……

我去下那张已经泛黄但依旧崭新的照片，在奶奶的棺木前将它点燃，嚎啕大哭……